# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0af0129d107f895d9e18f16122c84b62723e392e45a71a5871474465187559fe2915f652cc71eef3afe04655ebf7dc277598bb884b4c8d90507c9446ebaca80c
  marvel_public_key: 70983311f1accbcba6326990f43506d2
  marvel_private_key: 62e6477d65569a892861c6a6fe423494edfa9c0c
  marvel_candidates_url: https://gateway.marvel.com:443/v1/public/characters
  acclaim_url: https://sandbox-api.youracclaim.com/v1/organizations/f29e20dc-cef4-498e-b9dd-01fec5191b75
  acclaim_token: PLQD7d0Ru5iBCUohFMd_oMzurJegQ6ZpOZhikSL7

test:
  secret_key_base: bdb119248d1ee67b2691330a492a9122950d0fb1693c08056833a893dfd840e4b67712cb0b1316d74ba08cb1e4a66bb609f0b32a1956bbd0b157dc9e685ea1ce

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
